import java.util.*; 
class Q2
{ 
    public static void main(String arg[]) 
    { 
        Scanner sc=new Scanner(System.in); 
        System.out.println("enter number 1"); 
        int a=sc.nextInt(); 
        System.out.println("enter number 2"); 
        int b=sc.nextInt(); 
        System.out.println("enter number 3"); 
        int c=sc.nextInt(); 
        System.out.println("enter number 4"); 
        int d=sc.nextInt(); 
        System.out.println(a+"*"+b+"="+(a*b)); 
         System.out.println(c+"/"+d+"="+(double)(c/d)); 
 
    }
}

